### PR TITLE
Fix No .env file WARN if misleading #110

### LINKED ISSUE #110: No .env file WARN if misleading
**Bug**
`WARN[2019-07-19 23:23:09] open .env: no such file or directory` this warning is kinda misleading. This makes a user wonder if having a `.env` is mandatory.
THis

**To Reproduce**
1. Run any dunner task 

**Expected behaviour**
This ideally should be an INFO message. eg: `INFO[2019-07-19 23:23:09] No .env file found`

### PR DESCRIPTION
**Pull request by apoorvam**
Previously: 

```
WARN[2019-07-19 23:23:09] open .env: no such file or directory
```

Now:
 
```
INFO[2019-07-23 11:43:40] No environment loaded from .env file: open .env: no such file or directory
```

Fixes #110

### CODE REVIEW

**Comment by agentmilindu** [comment]
I feel like `open .env: no such file or directory` is nor needed. How about `No environment loaded from .env file: No .env found`?

File: pkg/config/config.go [hunk 1]
```diff
@@ -271,7 +271,7 @@ func loadDotEnv() {
 	var err error
 	dotEnv, err = godotenv.Read(file)
 	if err != nil {
-		log.Warn(err)
+		log.Infof("No environment loaded from %s file: %s", file, err.Error())
```
Comment (agentmilindu) [inline pkg/config/config.go]: I feel like `open .env: no such file or directory` is not needed. How about `No environment loaded from .env file: No .env found`?

Comment (apoorvam) [reply pkg/config/config.go]: Updated to: `No environment loaded from .env file: Not found`
